package com.compiler.Engine.compiler.escaner;

public enum TokenType {
    //PALABRAS RESERVADAS
    AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO, DOUBLE,
    ELSE, ENUM, EXTERN, FLOAT, FOR, GOTO, IF, INT, LONG, REGISTER,
    RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT, SWITCH, TYPEDEF,
    UNION, UNSIGNED, VOID, VOLATILE, WHILE, PACKED,

    //OPERADORES
    MUL, DIV, MOD, PLUS, MINUS, ASSIGN,
    SHL, SHR,
    LT, GT, LE, GE, EQ, NE,
    AND, OR, XOR, LAND, LOR,
    COMMA, NOT, INC,

    //PUNTUACION
    LBRACE, RBRACE, LBRACKET, RBRACKET,
    LPAREN, RPAREN, SEMICOLON, HASH,
    BACKSLASH, APOSTROPHE,

    IDENTIFIER, NUMBER, REAL, EOF

}
